Imp: update debian files and license

diff --git a/cli/gradle/gradle/scripts/debian/postinst b/cli/gradle/gradle/scripts/debian/postinst
--- a/cli/gradle/gradle/scripts/debian/postinst
+++ b/cli/gradle/gradle/scripts/debian/postinst
@@ -1,5 +1,20 @@
 #!/bin/sh
 
+# Copyright (c) 2016 Open Baton (http://www.openbaton.org)
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#      http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+
 ##########################
 #### General Settings ####
 ##########################
@@ -11,82 +26,83 @@ set -u
 # Make available the functions defined in /lib/lsb/init-functions
 . /lib/lsb/init-functions
 
-# Set the soft limit for max open file desciptors
-ulimit -S -n 4096
-
 
 ##########################
 #### Global Variables ####
 ##########################
 
-USER="$(id -un 2>/dev/null || true)"
+OPENBATON_COMPONENT_NAME_FANCY="Command Line Interface (CLI)"
+OPENBATON_COMPONENT_NAME=cli
+OPENBATON_COMPONENT_RELATIVE_SUBPATH=cli
 
-OPENBATON_BASE=/usr
+OPENBATON_BASE_DIR=/usr
+OPENBATON_COMPONENT_EXE_DIR=${OPENBATON_BASE_DIR}/bin
+OPENBATON_COMPONENT_EXE=${OPENBATON_BASE_DIR}/bin/openbaton
 
-OPENBATON_CLI_JAR=${OPENBATON_BASE}/lib/openbaton/cli/cli-all-*.jar
+OPENBATON_COMPONENT_CONFIG_FILE=/etc/openbaton/openbaton-${OPENBATON_COMPONENT_NAME}.properties
+OPENBATON_COMPONENT_JAR_FILE_NAME=openbaton-${OPENBATON_COMPONENT_NAME}
+OPENBATON_COMPONENT_JAR_INSTALL_DIR=/usr/lib/openbaton/${OPENBATON_COMPONENT_RELATIVE_SUBPATH}
 
-OPENBATON_CLI_PROPERTIES_FILE=/etc/openbaton/cli/nfvo.properties
-OPENBATON_CLI_EXE=${OPENBATON_BASE}/bin/openbaton
+#OPENBATON_CLI_JAR=${OPENBATON_BASE}/lib/openbaton/cli/cli-all-*.jar
+#OPENBATON_CLI_PROPERTIES_FILE=/etc/openbaton/cli/nfvo.properties
+#OPENBATON_CLI_EXE=${OPENBATON_BASE}/bin/openbaton
 
 
-##############################
-#### Execution privileges ####
-##############################
+####################
+#### Open Baton ####
+####################
 
-checkBinary () {
-    if command -v $1 >/dev/null 2>&1 ; then
-        log_success_msg "Checking for '$1'"
-        return 0
+set_jar_version () {
+    openbaton_component_jar_file_name_versioned=$(ls -ct ${OPENBATON_COMPONENT_JAR_INSTALL_DIR} | grep "${OPENBATON_COMPONENT_JAR_FILE_NAME}" | grep "jar" | head -n 1)
+    if [ "${openbaton_component_jar_file_name_versioned}" = "" ]; then
+        log_failure_msg "The Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} is not installed (jar-file not found)"
+        exit 1
     else
-        log_failure_msg "Checking for '$1'"
-        return 1
+        sed -i "s@_openbaton_cli_jar=.*@_openbaton_cli_jar=${OPENBATON_COMPONENT_JAR_INSTALL_DIR}/${openbaton_component_jar_file_name_versioned}@g" ${OPENBATON_COMPONENT_EXE}
     fi
 }
 
-_ex='sh -c'
-if [ "${USER}" != 'root' ]; then
-    if checkBinary sudo; then
-        _ex='sudo -E sh -c'
-    elif checkBinary su; then
-        _ex='su -c'
-    fi
-fi
+#setCLIJarFolder () {
+#    export OPENBATON_CLI_JAR=${OPENBATON_CLI_JAR}
+#    export OPENBATON_CLI_EXE=${OPENBATON_CLI_EXE}
+#    sed -i "s@_openbaton_cli_jar=.*@_openbaton_cli_jar=${OPENBATON_CLI_JAR}@g" ${OPENBATON_COMPONENT_EXE}
+#}
 
-
-################################################
-#### Configure Open Baton NFVO installation ####
-################################################
-
-setCLIJarFolder () {
-    export OPENBATON_CLI_JAR=${OPENBATON_CLI_JAR}
-    export OPENBATON_CLI_EXE=${OPENBATON_CLI_EXE}
-    $_ex "sed -i "s@_openbaton_cli_jar=.*@_openbaton_cli_jar=${OPENBATON_CLI_JAR}@g" ${OPENBATON_CLI_EXE}"
-}
-
-
-##############
-#### MAIN ####
-##############
-
-fixOpenbatonExe () {
-    export OPENBATON_CLI_EXE=${OPENBATON_CLI_EXE}
-    $_ex "sed -i \"s@source gradle.properties@#source gradle.properties@g\" ${OPENBATON_CLI_EXE}"
+fix_openbaton_exe () {
+    #export OPENBATON_COMPONENT_EXE=${OPENBATON_COMPONENT_EXE}
+    sed -i "s@source gradle.properties@#source gradle.properties@g" ${OPENBATON_COMPONENT_EXE}
 }
 
 configure () {
-    log_success_msg "Configuring Open Baton CLI installation .."
-
-    setCLIJarFolder
-    $_ex "chmod a+x ${OPENBATON_CLI_EXE}"
+    log_success_msg "Configuring Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} installation .."
+    set_jar_version
+    chmod a+x ${OPENBATON_COMPONENT_EXE_DIR}/openbaton
     
     # Temporary fix TODO: do it properly
-    fixOpenbatonExe
+    fix_openbaton_exe
 
-    log_success_msg "Open Baton CLI installation completed"
-    
-    log_success_msg "To configure the CLI for your Open Baton installation type the following command and provide the inputs required."
-    log_success_msg "source ${OPENBATON_CLI_PROPERTIES_FILE}"
+    log_success_msg "Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} installation completed"
+    log_success_msg "To configure the Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} for your Open Baton installation type the following command and provide the inputs required:"
+    log_success_msg "   source ${OPENBATON_COMPONENT_CONFIG_FILE}"
 }
 
-
 configure
+
+
+
+#configure () {
+#    log_success_msg "Configuring Open Baton CLI installation .."
+#
+#    setCLIJarFolder
+#    $_ex "chmod a+x ${OPENBATON_CLI_EXE}"
+#    
+#    # Temporary fix TODO: do it properly
+#    fix_openbaton_exe
+#
+#    log_success_msg "Open Baton CLI installation completed"
+#    
+#    log_success_msg "To configure the CLI for your Open Baton installation type the following command and provide the inputs required."
+#    log_success_msg "source ${OPENBATON_CLI_PROPERTIES_FILE}"
+#}
+#
+#configure
